### ISSUE TITLE
On using deeper networks such as ResNet50

### ISSUE THREAD

**Issue by roysubhankar** [wiseodd/last_layer_laplace#8]
Hi,

First of all thanks for making the code public.

I am trying to use your method for making the last layer of a deeper neural network such as Resnet50 Bayesian. I have followed the code (LLLA) for cifar10 from your repo. However, I found that the variance in prediction for both in-distribution and out-of-distribution samples to lie in a similar range. In my case the ood classes are the same as the train set, just there is a big dataset/domain shift between the training and test distribution. Can you please tell me if this behaviour is expected or it has something to do with the neural network depth? Have you tried your method for resnet like networks?

Thank you.

**Comment by wiseodd** [comment]
Hi, have you tuned the prior variance/precision hyperparameter? The provided hyperparameter is specific to ResNet-18 and I would not expect it to work out-of-the-box with other architectures. 

Anyway, please use our new library `laplace-torch` (<https://github.com/AlexImmer/Laplace>) instead of this repository. It's easier to use, more flexible, and feature-rich. LLLA, and other state-of-the-art Laplace approximations, are available there.
